services:
  hydroapp:
    build: .
    container_name: hydroapp
    restart: unless-stopped
    expose:
      - "4567"
    environment:
      RACK_ENV: production
      PORT: 4567
      DATABASE_PATH: /app/data/hydro.sqlite3
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.hydroapp.rule=Host(`hydro.dqq.pl`)"
      - "traefik.http.routers.hydroapp.entrypoints=websecure"
      - "traefik.http.routers.hydroapp.tls=true"
      - "traefik.http.routers.hydroapp.tls.certresolver=myresolver"
      - "traefik.http.services.hydroapp.loadbalancer.server.port=4567"
    networks:
      - proxy

networks:
  proxy:
    external: true
